### ISSUE TITLE
Error on multi-line title

### ISSUE THREAD

**Issue by yxiong** [asm-products/Dissertate#29]
I am quite a novice to latex and apologize in advance if this rookie question is not related to the package itself.

When I was trying to make an multi-line title, and according to [this post](http://tex.stackexchange.com/questions/56222/how-to-make-a-title-of-two-or-more-lines), I should use

    \title{First line \\
    second line}

But I got the following error from the console:

    ! Argument of \reserved@a has an extra }.
    <inserted text>
                    \par
    l.3 second line}

Am I missing something here? And what is the right way to make a multi-line title in the `dissertate` package? Thanks!

**Comment by suchow** [comment]
Can you try:

```
\title{First line \protect\\
second line}
```

as per http://tex.stackexchange.com/a/136326?

Note the `\protect` before `\\`.

**Comment by yxiong** [comment]
Yep, that works! Thanks so much for the pointer!
